#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : unicodecsv
Version  : 0.14.1
Release  : 15
URL      : http://pypi.debian.net/unicodecsv/unicodecsv-0.14.1.tar.gz
Source0  : http://pypi.debian.net/unicodecsv/unicodecsv-0.14.1.tar.gz
Summary  : Python2's stdlib csv module is nice, but it doesn't support unicode. This module is a drop-in replacement which *does*.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: unicodecsv-python
BuildRequires : linecache2-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
BuildRequires : testtools
BuildRequires : traceback2-python
BuildRequires : unittest2-python

%description
==========
        
        The unicodecsv is a drop-in replacement for Python 2.7's csv module which supports unicode strings without a hassle.  Supported versions are python 2.7, 3.3, 3.4, 3.5, and pypy 2.4.0.
        
        More fully
        ----------
        
        Python 2's csv module doesn't easily deal with unicode strings, leading to the dreaded "'ascii' codec can't encode characters in position ..." exception.
        
        You can work around it by encoding everything just before calling write (or just after read), but why not add support to the serializer?

%package python
Summary: python components for the unicodecsv package.
Group: Default

%description python
python components for the unicodecsv package.


%prep
%setup -q -n unicodecsv-0.14.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503082454
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1503082454
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
