#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : unicodecsv
Version  : 0.14.1
Release  : 17
URL      : https://files.pythonhosted.org/packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz
Summary  : Python2's stdlib csv module is nice, but it doesn't support unicode. This module is a drop-in replacement which *does*.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: unicodecsv-python3
Requires: unicodecsv-python
BuildRequires : buildreq-distutils3
BuildRequires : linecache2-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
BuildRequires : testtools
BuildRequires : traceback2-python
BuildRequires : unittest2-python

%description
==========
        
        The unicodecsv is a drop-in replacement for Python 2.7's csv module which supports unicode strings without a hassle.  Supported versions are python 2.7, 3.3, 3.4, 3.5, and pypy 2.4.0.
        
        More fully
        ----------
        
        Python 2's csv module doesn't easily deal with unicode strings, leading to the dreaded "'ascii' codec can't encode characters in position ..." exception.
        
        You can work around it by encoding everything just before calling write (or just after read), but why not add support to the serializer?

%package python
Summary: python components for the unicodecsv package.
Group: Default
Requires: unicodecsv-python3

%description python
python components for the unicodecsv package.


%package python3
Summary: python3 components for the unicodecsv package.
Group: Default
Requires: python3-core

%description python3
python3 components for the unicodecsv package.


%prep
%setup -q -n unicodecsv-0.14.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532377865
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
